site_name: amigus.dnsmasq
repo_url: https://github.com/amigus/dnsmasq-ansible
site_url: https://amigus.github.io/dnsmasq-ansible/
docs_dir: docs
nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Roles:
    - dnsmasq: roles/dnsmasq.md
    - dnsmasq_install: roles/dnsmasq_install.md
    - dnsmasq_dhcp: roles/dnsmasq_dhcp.md
    - dnsmasq_dhcp_db: roles/dnsmasq_dhcp_db.md
    - dnsmasq_dns: roles/dnsmasq_dns.md
    - dnsmasq_web: roles/dnsmasq_web.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.follow
    - toc.integrate
    - content.code.annotate
    - content.code.copy
markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji
plugins:
  - search
  - include-markdown
