---
- name: "Use the default interface for DNS"
  when: dnsmasq_dns_interfaces is defined and dnsmasq_dns_interfaces == 'default'
  ansible.builtin.set_fact:
    dnsmasq_dns_interfaces: "{{ [ansible_facts['default_ipv4']['interface']] }}"

- name: Configure Dnsmasq as a DNS resolver
  notify: Restart dnsmasq service
  block:
    - name: "Create the DNS configuration"
      tags: [dns]
      ansible.builtin.template:
        dest: "{{ dnsmasq_dns_conf_file }}"
        mode: "0644"
        src: "conf.j2"

    - name: "Setup DNS hosts file"
      tags: [dns, hosts]
      when: dnsmasq_dns_hosts is defined
      ansible.builtin.copy:
        content: "{{ dnsmasq_dns_hosts }}"
        dest: "{{ dnsmasq_dns_hosts_file }}"
        mode: "0644"
