---
name: Deploy MkDocs site to GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: pip install \
          mkdocs-material \
          mkdocs-include-markdown-plugin \
          pymdown-extensions

      - run: mkdocs gh-deploy --force
